# Predict real data patches with previous models

In this notebook we are going to make some example predictions with the best models for the coast of Pollença.

#### Import necessary libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import rasterio

import tensorflow as tf
from tensorflow.keras import Model, layers

import keras
import os

2025-06-27 13:21:53.851148: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-27 13:21:54.068395: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-27 13:21:54.949211: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-27 13:21:54.952946: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-27 13:21:57.751182: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:3

#### Read a patch

In [2]:
# Los que no son nada devuelven nan en el sitio, el resto da 0 o 1 si hay posidonia o no

ds = rasterio.open('Data/Patches/Mallorca_EsteNorte/patch_0_4.tif')

data = ds.read(1)
print(data)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


#### Predict the pattern

In [25]:
im_height=256
im_width=256

model_path = f"modelos/Cmodel_18.h5"
model = tf.keras.models.load_model(model_path)


# (hexagonos, hexagonos vacios, homogenea, rayas, vacia) = (0, 1, 2, 3, 4)
class_prediction = np.argmax(model.predict(data.reshape(1, im_height, im_width)))
print(class_prediction)

prediction = class_prediction * np.ones([im_height, im_width])

print(prediction)

1/1 [==============================] - 0s 43ms/step
4
[[4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 ...
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]]


#### Predict the mortality

In [3]:
im_height=256
im_width=256

model_path = f"modelos/Dmodel_14.h5"
model = tf.keras.models.load_model(model_path)


class_prediction = model.predict(data.reshape(1, im_height, im_width))
print(class_prediction)

prediction = class_prediction * np.ones([im_height, im_width])

print(prediction)

2025-06-27 13:22:57.076528: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


1/1 [==============================] - 0s 271ms/step
[[0.34387684]]
[[0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]
 [0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]
 [0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]
 ...
 [0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]
 [0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]
 [0.34387684 0.34387684 0.34387684 ... 0.34387684 0.34387684 0.34387684]]
